version: '3.8'
services:
  nuxt-front:
    build: ./nuxt
    ports:
      - 9000:3000
    volumes:
      - ./nuxt/src:/workspace
    working_dir: /workspace
  flask-back:
    build: ./flask
    ports:
      - 5000:5000
    volumes:
      - ./flask/src:/workspace
    